services:
  - type: web
    name: leadcaptura
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      NODE_ENV: production

    # BANCO PERSISTENTE (NUNCA PERDE USU√ÅRIOS)
    disks:
      - name: data
        mountPath: /opt/render/project/src/server/database
        sizeGB: 1
